packages: []
catalogs:
  build:
    tsdown: ^0.15.1
  cli:
    '@vscode/vsce': ^3.6.0
    bumpp: ^10.2.3
    ovsx: ^0.10.5
    pncat: ^0.5.4
    taze: ^19.6.0
  dev:
    typescript: ^5.9.2
  lint:
    '@antfu/eslint-config': ^5.3.0
    eslint: ^9.35.0
    lint-staged: ^16.1.6
    simple-git-hooks: ^2.13.1
  test:
    vitest: ^3.2.4
  types:
    '@types/node': ^24.5.0
  utils:
    comment-json: ^4.2.5
  vscode:
    reactive-vscode: ^0.3.2
    vscode-ext-gen: ^1.1.0
