packages: []
catalogs:
  build:
    tsdown: ^0.16.3
  cli:
    '@vscode/vsce': ^3.7.0
    bumpp: ^10.3.1
    pncat: ^0.7.5
    taze: ^19.9.0
  lint:
    '@antfu/eslint-config': ^6.2.0
    eslint: ^9.39.1
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
  network:
    ofetch: ^1.5.1
  test:
    vitest: ^4.0.8
  tsc:
    typescript: ^5.9.3
  types:
    '@types/node': ^24.10.1
  utils:
    comment-json: ^4.4.1
  vscode:
    reactive-vscode: ^0.4.1
    vscode-ext-gen: ^1.4.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - '@vscode/vsce-sign'
  - keytar
